name: 'Build Documentation'
description: 'Build all documentation (main + examples) for jsoncrack-for-sphinx'
outputs:
  site-path:
    description: 'Path to the built site'
    value: ${{ steps.build.outputs.site-path }}
runs:
  using: 'composite'
  steps:
    - name: Build main documentation
      shell: bash
      run: |
        cd docs
        sphinx-build -b html . _build/html
        
    - name: Build examples documentation
      shell: bash
      run: |
        cd examples/docs
        sphinx-build -b html . _build/html
        
    - name: Prepare site structure
      id: build
      shell: bash
      run: |
        # Create main site structure
        mkdir -p _site
        cp -r docs/_build/html/* _site/
        
        # Add coverage report
        mkdir -p _site/coverage
        cp -r htmlcov/* _site/coverage/
        
        # Add examples
        mkdir -p _site/examples
        cp -r examples/docs/_build/html/* _site/examples/
        
        # Add coverage badge
        cp coverage.svg _site/

        # Add tests report
        mkdir -p _site/tests
        cp -r tests-report.html _site/tests/

        # Add tests badge
        cp tests-badge.svg _site/

        echo "site-path=_site" >> $GITHUB_OUTPUT
