name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Build main documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html
        
    - name: Build examples documentation
      run: |
        cd examples/docs
        sphinx-build -b html . _build/html
        
    - name: Run tests for coverage
      run: |
        pytest --cov=jsoncrack_for_sphinx --cov-report=html --cov-report=xml
        
    - name: Generate coverage badge
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg
        
    - name: Prepare site structure
      run: |
        mkdir -p _site
        cp -r docs/_build/html/* _site/
        
        # Add coverage report
        mkdir -p _site/coverage
        cp -r htmlcov/* _site/coverage/
        
        # Add examples
        mkdir -p _site/examples
        cp -r examples/docs/_build/html/* _site/examples/
        
        # Add coverage badge
        cp coverage.svg _site/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true
